/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.ArticuloDao;
import Controlador.Controlador;
import javax.swing.JOptionPane;
import sistema.Configuracion;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class FramePrincipal extends javax.swing.JFrame {

    boolean e=false;
    
    public FramePrincipal(boolean e) {
        initComponents();
        
        if(Configuracion.usuario.getUsuario().equalsIgnoreCase("admin")){
            
             this.menuGestion.setEnabled(true);
        }else{
           this.menuGestion.setEnabled(false);
        }
        this.e = e;
        
      
        Configuracion.control.setFramePrincipal(this);
        
    }

    private FramePrincipal() {
      
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioMochila = new javax.swing.JDesktopPane();
        Jmenu = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemArticulo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMochila = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemCaja = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        setSize(new java.awt.Dimension(986, 769));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        escritorioMochila.setPreferredSize(new java.awt.Dimension(989, 704));

        javax.swing.GroupLayout escritorioMochilaLayout = new javax.swing.GroupLayout(escritorioMochila);
        escritorioMochila.setLayout(escritorioMochilaLayout);
        escritorioMochilaLayout.setHorizontalGroup(
            escritorioMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 989, Short.MAX_VALUE)
        );
        escritorioMochilaLayout.setVerticalGroup(
            escritorioMochilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        getContentPane().add(escritorioMochila, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        menuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GestionIcon.jpg"))); // NOI18N
        menuGestion.setText("GESTION");

        itemUsuario.setText("USUARIOS");
        itemUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemUsuarioMouseClicked(evt);
            }
        });
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        menuGestion.add(itemUsuario);

        itemArticulo.setText("ARTICULOS");
        itemArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArticuloActionPerformed(evt);
            }
        });
        menuGestion.add(itemArticulo);

        Jmenu.add(menuGestion);

        jMenu2.setText("MOCHILA");

        itemMochila.setText("ENTER");
        itemMochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMochilaActionPerformed(evt);
            }
        });
        jMenu2.add(itemMochila);

        Jmenu.add(jMenu2);

        jMenu3.setText("CAJA");

        itemCaja.setText("ENTER");
        itemCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCajaActionPerformed(evt);
            }
        });
        jMenu3.add(itemCaja);

        Jmenu.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/indeci.jpg"))); // NOI18N
        jMenu1.setText("jMenu1");
        jMenu1.setFocusable(false);
        jMenu1.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMenu1.setPreferredSize(new java.awt.Dimension(500, 61));
        Jmenu.add(jMenu1);

        jMenu4.setText("INFO");

        jMenuItem5.setText("NECESARIO");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("INDISPENSABLE");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        Jmenu.add(jMenu4);

        jMenu5.setText("CUENTA");

        jMenuItem7.setText("Logout");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        Jmenu.add(jMenu5);

        setJMenuBar(Jmenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMochilaActionPerformed
        // TODO add your handling code here:
        FrameIntMochila frm = new FrameIntMochila();
        this.escritorioMochila.removeAll();
        this.escritorioMochila.add(frm);
        
        frm.show();
    }//GEN-LAST:event_itemMochilaActionPerformed

    private void itemCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCajaActionPerformed
        // TODO add your handling code here:
        FrameIntCaja frm = new FrameIntCaja();
        this.escritorioMochila.removeAll();
        this.escritorioMochila.add(frm);
        
        frm.show();
        
    }//GEN-LAST:event_itemCajaActionPerformed

    private void itemArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArticuloActionPerformed
        // TODO add your handling code here:
     
        
        FrameIntGestionArticulo frm = new FrameIntGestionArticulo();
        this.escritorioMochila.removeAll();
        this.escritorioMochila.add(frm);
        
        frm.show();
       
        
    }//GEN-LAST:event_itemArticuloActionPerformed

    private void itemUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemUsuarioMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itemUsuarioMouseClicked

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
        FrameIntGestionUsuarios frm = new FrameIntGestionUsuarios();
        this.escritorioMochila.removeAll();
        this.escritorioMochila.add(frm);
        
        frm.show();
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
         FrameInfo frm = new FrameInfo("INDISPENSABLE");
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FrameInfo frm = new FrameInfo("NECESARIO");
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Vuelva pronto....", "CERRANDO SESION", 1);
        
        if(e){
             FrameLogin frm = new FrameLogin(Configuracion.usuario.getUsuario(),Configuracion.usuario.getContraseña());
             frm.setLocationRelativeTo(null);
             frm.setVisible(true);
             this.dispose();
        }else{
             FrameLogin frm = new FrameLogin("","");
             frm.setLocationRelativeTo(null);
             frm.setVisible(true);
             this.dispose();
        }
        
       
        
        
        Configuracion.usuario.cerrarSesion();
        Configuracion.usuario=null;
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    
    
    
  
    
    
   
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar Jmenu;
    private javax.swing.JDesktopPane escritorioMochila;
    public javax.swing.JMenuItem itemArticulo;
    public javax.swing.JMenuItem itemCaja;
    public javax.swing.JMenuItem itemMochila;
    public javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    public javax.swing.JMenu menuGestion;
    // End of variables declaration//GEN-END:variables
}
