/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Usuario;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import sistema.Configuracion;

/**
 *
 * @author USUARIO
 */
public class FrameIntGestionUsuarios extends javax.swing.JInternalFrame {

    
    boolean e=false;
    public FrameIntGestionUsuarios() {
        initComponents();
        if(Configuracion.usuario.getUsuario().equalsIgnoreCase("admin")){
            cargarTabla();
            this.botones(true);
        }else{
            this.botones(false);
        }
    }
    
    public FrameIntGestionUsuarios(boolean e) {
        initComponents();
        this.botones(false);
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(990, 704));
        setPreferredSize(new java.awt.Dimension(990, 704));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("LISTA DE USUARIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 270, 30));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 180, 30));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 153, 0));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 110, 60));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 153, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 60));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 180, 30));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 410, 270));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CONTRASEÑA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 140, 20));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, 30));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 153, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NOMBRE:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 120, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("USUARIO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("GESTION DE USUARIOS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 310, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        ;

        try{

            if(!this.validarFormAgregar()){

            }else{

                int confirmado = JOptionPane.showConfirmDialog(this,"¿seguro?");

                if(JOptionPane.OK_OPTION==confirmado){

                    Configuracion.usuarios.add(new Usuario(this.txtUsuario.getText(),
                        this.txtContraseña.getText(), this.txtNombre.getText()));

                JOptionPane.showMessageDialog(this, "AGREGADO EXITOSAMENTE");
                this.limpiar();
                cargarTabla();

                if(e){
                    this.dispose();
                }

            }

        }

        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ERROR");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        try{
            
            int fila=0;
            int columna =1;
            String nombreU="";
           
            Usuario usuario;
             
            fila=this.tablaUsuarios.getSelectedRow();
            
            nombreU = (String)this.tablaUsuarios.getValueAt(fila,columna);
            
            
     
            usuario =Configuracion.usuarios.obtenerUsuario(nombreU);
            
      
      
           if(usuario != null){
                
                int confirmado = JOptionPane.showConfirmDialog(this,"¿seguro?");
                
                if(JOptionPane.OK_OPTION==confirmado){
                    
                     Configuracion.usuarios.eliminar(usuario.getUsuario()); //eliminado usuario
                     
                    JOptionPane.showMessageDialog(this, "Eliminado exitosamente");
                    this.limpiar();
                    cargarTabla();
                     
                }
                   
               
            }else{
                JOptionPane.showMessageDialog(this,"Usuario no encontrado");
            }

          
         this.cargarTabla();
            
        }catch(IndexOutOfBoundsException p){
            JOptionPane.showMessageDialog(this, "ElEMENTO NO SELECCIONADO: "+p);
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    
    //---------------------------------------------------
    
     public void cargarTabla(){
    
    DefaultTableModel table = new DefaultTableModel(Configuracion.usuarios.getMatrizUsuario(),
                                        Configuracion.usuarios.getTitulos());
        this.tablaUsuarios.setModel(table);
        this.tablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);  
       
            
    
    
}
    
    private boolean validarFormAgregar(){
        boolean result = false;
        if(this.txtNombre.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "INTRODUZCA SU NOMBRE", "NOMBRE", ERROR_MESSAGE);
        
        }else if(this.txtUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA EL USUARIO", "USUARIO",ERROR_MESSAGE);
            
        }else if(this.txtContraseña.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "INTRODUZCA LA CONTRASEÑA", "CONTRASEÑA", ERROR_MESSAGE);
        }else if(Configuracion.usuarios.findUsuario(txtUsuario.getText())){
            JOptionPane.showMessageDialog(this, "USER YA REGISTRADO ", "USER", ERROR_MESSAGE);
        }
        
        else{
            result = true;
        }
        return result;     
    } 


    
     private void limpiar(){
   
         this.txtNombre.setText("");
        this.txtUsuario.setText("");
         this.txtContraseña.setText("");
    }
    
    private void botones(boolean e){
        
        this.btnEliminar.setEnabled(e);
        this.tablaUsuarios.setEnabled(e);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
